name: manage_malaebna
description: "An app for managing football pitches"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0 # For state management
  equatable: ^2.0.5 # For comparing objects in bloc
  shared_preferences: ^2.2.2 # For storing local preferences
  smooth_page_indicator: ^1.1.0 # For onboarding page indicator
  sqflite: ^2.3.2
  path: ^1.8.3
  supabase_flutter: ^2.4.0
  uuid: ^4.2.1
  connectivity_plus: ^6.1.3

  image_picker: ^1.1.2
  #flutter_image_compress: ^2.4.0 # Temporarily disabled due to Kotlin compatibility issues
  sentry_flutter: ^8.14.1
  path_provider: ^2.1.5

  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  geolocator_android: ^4.5.0 # Pinning to a specific version for compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # App branding and splash screen
  flutter_native_splash: ^2.3.10 # For splash screen configuration
  flutter_launcher_icons: ^0.13.1 # For app icon generation

# To run the splash screen generation:
# flutter pub run flutter_native_splash:create
# To remove the splash screen:
# flutter pub run flutter_native_splash:remove

# Run this to update app icons:
# flutter pub run flutter_launcher_icons

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/stadium/
    - assets/translations/
    - assets/images/logo/
