name: Build Flutter iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..
          
      - name: Build unsigned app
        run: |
          flutter clean
          flutter build ios --no-codesign --release --verbose
          
          # Create IPA manually
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          cd ../../../
          
          if [ ! -f "build/ios/ipa/Runner.ipa" ]; then
            echo "::error::IPA file not generated!"
            ls -la build/ios/ipa/
            exit 1
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner-IPA
          path: build/ios/ipa/Runner.ipa
