name: Build Flutter iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Match your local version
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..
          
      - name: Build IPA (Development)
        run: |
          flutter clean
          flutter build ipa \
            --export-method development \
            --no-codesign \
            --obfuscate \
            --split-debug-info=./debug_info \
            --release
          
          # Verify IPA exists
          if [ ! -f "build/ios/ipa/Runner.ipa" ]; then
            echo "::error::IPA file not generated!"
            ls -la build/ios/ipa/
            exit 1
          fi
          
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: Runner-IPA
          path: build/ios/ipa/Runner.ipa
          retention-days: 7
