name: Build Flutter iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Match your local version
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..
          
      - name: Build IPA
        run: |
          flutter clean
          flutter build ipa \
            --export-method development \
            --no-codesign \
            --obfuscate \
            --split-debug-info=./debug_info \
            --release
            
          if [ ! -f "build/ios/ipa/Runner.ipa" ]; then
            echo "::error::IPA file not generated!"
            exit 1
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Runner.ipa
          path: build/ios/ipa/Runner.ipa
